<?php
namespace Apigee\Mint;

// TODO: finish this class when the docs are finished

class DeveloperSubscriptionDetail extends Base\BaseObject
{

    private $developerId;
    private $productId;

    private $id;

    public function __construct($developer_id, $product_id, \Apigee\Util\OrgConfig $config)
    {
        $base_url = '/mint/organizations/'
            . rawurlencode($config->orgName)
            . '/developers/'
            . rawurlencode($developer_id)
            . '/products/'
            . rawurlencode($product_id)
            . '/subscriptions_details';
        $this->init($config, $base_url);

        $this->developerId = $developer_id;
        $this->productId = $product_id;

        $this->wrapperTag = 'developerSubscriptionDetail';
        // TODO: verify the following two items when docs are fleshed out
        $this->idField = 'id';
        $this->idIsAutogenerated = true;

        $this->initValues();
    }

    protected function initValues()
    {
        // TODO
        $this->id = null;
    }

    public function instantiateNew()
    {
        return new DeveloperSubscriptionDetail($this->developerId, $this->productId, $this->config);
    }

    public function loadFromRawData($data, $reset = false)
    {
        if ($reset) {
            $this->initValues();
        }
        $properties = array_keys(get_object_vars($this));
        $excluded_properties = array_keys(get_class_vars(get_parent_class($this)));
        $excluded_properties += array(
            'developerId',
            'productId',
        );
        foreach ($properties as $property) {
            if (in_array($property, $excluded_properties)) {
                continue;
            }
            if (isset($data[$property])) {
                $this->$property = $data[$property];
            }
        }
    }

    public function __toString()
    {
        $obj = array();
        $properties = array_keys(get_object_vars($this));
        $excluded_properties = array_keys(get_class_vars(get_parent_class($this)));
        $excluded_properties += array(
            'developerId',
            'productId',
        );
        foreach ($properties as $property) {
            if (in_array($property, $excluded_properties)) {
                continue;
            }
            if (isset($this->$property)) {
                $obj[$property] = $this->$property;
            }
        }
        return json_encode($obj);
    }

    public function getId()
    {
        return $this->id;
    }

    // Used in data load invoked by $this->loadFromRawData()
    private function setId($id)
    {
        $this->id = $id;
    }
}
